### ISSUE TITLE
running the build-iso script on local seems to get stuck on 'github_echo' statement

### ISSUE THREAD

**Issue by timkenhan** [MX-Linux/build-iso-mx#54]
what are this github integration all about anyway?

it's stuck specifically on line 2158 of `build-iso` on `_check_errors_()`:  
````
github_echo "Checking for $(pq $type) errors @offset $ERROR_OFFSET"
````

**Comment by timkenhan** [comment]
@AdrianTM @dolphinoracle what's your take on this?

**Comment by AdrianTM** [comment]
@jhsu802701 can you help with this?

If this github integration creates problems I will have to pull all the code back.

Personally, I think the integration makes more sense for compiled languages to check if the commits compile fine or even to build .debs automatically, in a case of a script that we use to build ISOs I think only a cursory check could be done to see if the script is valid, maybe check some outputs, but I don't think we need to build ISOs automatically. I think we jumped head down into this without knowing what the objectives are. I let this go because I also didn't understand where is going and wanted to see and learn new things but if it creates problems it might be time to step back and reconsider.

Also @jhsu802701 would it be possible to move all your commits to a test CI branch to demonstrate how things work, and then if we are happy with the results we can merge that to main branch.

**Comment by timkenhan** [comment]
It would be great if we can see the configuration at least. I am currently using vanilla installation of Debian with the packages listed on the README. It's been working with no issue until the recent changes.

**Comment by AdrianTM** [comment]
I reverted github integration commits in master, they are still in workflows branch where we can continue the work and testing and if we are happy with the result we can merge them to master.

**Comment by timkenhan** [comment]
thank you @AdrianTM, will be closing this
