### ISSUE TITLE
Updating glibc and so forth?

### ISSUE THREAD

**Issue by rubyFeedback** [MX-Linux/build-iso-mx#58]
Hey guys,

I recently installed MX Linux. It comes with glibc 2.31.

Mageia Linux comes with glibc 2.36.

I tend to compile everything from source and I'd love to use non-systemd centric distributions
but upgrading glibc is quite painful, so I kind of prefer distributions that make it easy to 
upgrade. Could you perhaps upgrade MX Linux' glibc version? I understand that it takes
testing, but perhaps there is some testing done wrong internally at MX Linux to explain
why it is so slow to update things. I think even ubuntu has a more recent glibc at this
point in time.

**Comment by dolphinoracle** [comment]
debian does update base system files more slowing than other distros.   we are on glibc 2.31 instead of 2.36 because that is where debian is currently on stable, and we follow debian stable pretty closely.

due to dependency chains, updated glibc (and libc and ohters built from the same source) is non trivial for a stable release distro.

the next version of debian (later this year) has 2.36 I believe.
